title: ML Conference Deadlines
description: ML conference deadlines
author: TNT

domain: "https://ml-deadlines.github.io/"
baseurl: "https://ml-deadlines.github.io/ml-deadlines"

twitter_hashtag: machinelearning
github_username: ml-deadlines
github_repo: ml-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
